name: snap-pulse
description: |
  SnapPulse - A self-hosted analytics platform for Snap Store packages.
  Provides data collection, API endpoints, dashboard, and AI-powered optimization suggestions.

applications:
  collector:
    charm: ./charms/collector
    num_units: 1
    options:
      snap-name: "firefox"
    
  api:
    charm: ./charms/api
    num_units: 1
    expose: true
    
  dashboard:
    charm: ./charms/dashboard
    num_units: 1
    expose: true
    options:
      api-url: "http://api:8000"
      
  copilot:
    charm: ./charms/copilot
    num_units: 1
    options:
      github-token: ""  # Set this to your GitHub token

relations:
  - [api:api-endpoint, dashboard:api]
