name: snap-pulse
applications:
  collector:
    charm: ./charms/collector.charm
    resources:
      collector-image: ghcr.io/example/snap-pulse-collector:latest
  api:
    charm: ./charms/api.charm
    resources:
      api-image: ghcr.io/example/snap-pulse-api:latest
  dashboard:
    charm: ./charms/dashboard.charm
    resources:
      dash-image: ghcr.io/example/snap-pulse-dashboard:latest
  copilot:
    charm: ./charms/copilot.charm
    resources:
      copilot-image: ghcr.io/example/snap-pulse-copilot:latest
relations:
- [collector, api]
- [api, dashboard]
- [api, copilot]
