name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black yamllint pytest httpx fastapi

    - name: Check Python formatting with Black
      run: black --check .

    - name: Lint YAML files
      run: yamllint -s .

    - name: Run Python syntax checks
      run: |
        python -m py_compile snap-pulse/services/api/main.py
        python -m py_compile snap-pulse/services/collector/app.py
        python -m py_compile snap-pulse/services/copilot/main.py
        find snap-pulse/charms -name "*.py" -exec python -m py_compile {} \;
          
    - name: Run tests
      run: |
        cd tests && python -m pytest -v
        yamllint snap-pulse/kubernetes/
        yamllint snap-pulse/charms/*/charmcraft.yaml
        yamllint snap-pulse/snap/snapcraft.yaml

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest httpx fastapi uvicorn

    - name: Run API tests
      run: |
        cd snap-pulse/services/api
        python -m pytest ../../tests/ -v

    - name: Run Copilot tests
      run: |
        cd snap-pulse/services/copilot
        python -m pytest ../../tests/ -v

  charmcraft-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install charmcraft
      run: |
        sudo snap install charmcraft --classic

    - name: Lint charms
      run: |
        cd snap-pulse/charms/api && charmcraft lint
        cd ../collector && charmcraft lint
        cd ../dashboard && charmcraft lint
        cd ../copilot && charmcraft lint
